//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1433
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.I18N", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar.
        /// </summary>
        internal static string Activar {
            get {
                return ResourceManager.GetString("Activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir respuesta.
        /// </summary>
        internal static string AnadirRespuesta {
            get {
                return ResourceManager.GetString("AnadirRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir una respuesta.
        /// </summary>
        internal static string AnadirUnaRespuesta {
            get {
                return ResourceManager.GetString("AnadirUnaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string Anterior {
            get {
                return ResourceManager.GetString("Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apuntarse.
        /// </summary>
        internal static string Apuntarse {
            get {
                return ResourceManager.GetString("Apuntarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        internal static string Archivo {
            get {
                return ResourceManager.GetString("Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ascendente.
        /// </summary>
        internal static string ascendente {
            get {
                return ResourceManager.GetString("ascendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor.
        /// </summary>
        internal static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De.
        /// </summary>
        internal static string autormensaje {
            get {
                return ResourceManager.GetString("autormensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        internal static string Añadir {
            get {
                return ResourceManager.GetString("Añadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir comentario.
        /// </summary>
        internal static string AñadirComentario {
            get {
                return ResourceManager.GetString("AñadirComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir un comentario.
        /// </summary>
        internal static string AñadirUnComentario {
            get {
                return ResourceManager.GetString("AñadirUnComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por.
        /// </summary>
        internal static string BuscarPor {
            get {
                return ResourceManager.GetString("BuscarPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        internal static string Cambiar {
            get {
                return ResourceManager.GetString("Cambiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuestas.
        /// </summary>
        internal static string CantidadEncuestas {
            get {
                return ResourceManager.GetString("CantidadEncuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firmas.
        /// </summary>
        internal static string CantidadFirmas {
            get {
                return ResourceManager.GetString("CantidadFirmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imágenes.
        /// </summary>
        internal static string CantidadImagenes {
            get {
                return ResourceManager.GetString("CantidadImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad por página.
        /// </summary>
        internal static string CantidadPorPagina {
            get {
                return ResourceManager.GetString("CantidadPorPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        internal static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías.
        /// </summary>
        internal static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contrasena {
            get {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        internal static string ContraseñaActual {
            get {
                return ResourceManager.GetString("ContraseñaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña anterior.
        /// </summary>
        internal static string ContraseñaAnterior {
            get {
                return ResourceManager.GetString("ContraseñaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        internal static string CorreoElectronico {
            get {
                return ResourceManager.GetString("CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a creado por.
        /// </summary>
        internal static string creadoPor {
            get {
                return ResourceManager.GetString("creadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nuevo grupo.
        /// </summary>
        internal static string CrearGrupo {
            get {
                return ResourceManager.GetString("CrearGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nuevo hilo.
        /// </summary>
        internal static string CrearNuevoHilo {
            get {
                return ResourceManager.GetString("CrearNuevoHilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del usuario.
        /// </summary>
        internal static string DatosUsuario {
            get {
                return ResourceManager.GetString("DatosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De.
        /// </summary>
        internal static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes identificarte.
        /// </summary>
        internal static string DebesIdentificarte {
            get {
                return ResourceManager.GetString("DebesIdentificarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes identificarte para crear hilos.
        /// </summary>
        internal static string DebesIdentificarteCrearHilos {
            get {
                return ResourceManager.GetString("DebesIdentificarteCrearHilos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar una categoría.
        /// </summary>
        internal static string DebesSeleccionarCategoria {
            get {
                return ResourceManager.GetString("DebesSeleccionarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        internal static string Deminuscula {
            get {
                return ResourceManager.GetString("Deminuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desactivar.
        /// </summary>
        internal static string Desactivar {
            get {
                return ResourceManager.GetString("Desactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha desapuntado correctamente del grupo.
        /// </summary>
        internal static string DesapuntarGrupo {
            get {
                return ResourceManager.GetString("DesapuntarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desapuntarse.
        /// </summary>
        internal static string Desapuntarse {
            get {
                return ResourceManager.GetString("Desapuntarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        internal static string Descargar {
            get {
                return ResourceManager.GetString("Descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargas.
        /// </summary>
        internal static string Descargas {
            get {
                return ResourceManager.GetString("Descargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descendente.
        /// </summary>
        internal static string descendente {
            get {
                return ResourceManager.GetString("descendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        internal static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar datos.
        /// </summary>
        internal static string EditarDatos {
            get {
                return ResourceManager.GetString("EditarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la categoría actual.
        /// </summary>
        internal static string EnCategoriaActual {
            get {
                return ResourceManager.GetString("EnCategoriaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a encontrados.
        /// </summary>
        internal static string EncontradosMin {
            get {
                return ResourceManager.GetString("EncontradosMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuestas.
        /// </summary>
        internal static string Encuestas {
            get {
                return ResourceManager.GetString("Encuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En todas las categorías.
        /// </summary>
        internal static string EnTodasCategorias {
            get {
                return ResourceManager.GetString("EnTodasCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar comentario.
        /// </summary>
        internal static string EnviarComentario {
            get {
                return ResourceManager.GetString("EnviarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar material.
        /// </summary>
        internal static string EnviarMaterial {
            get {
                return ResourceManager.GetString("EnviarMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Mensaje.
        /// </summary>
        internal static string Enviarmensaje {
            get {
                return ResourceManager.GetString("Enviarmensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar respuesta.
        /// </summary>
        internal static string EnviarRespuesta {
            get {
                return ResourceManager.GetString("EnviarRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estás aquí.
        /// </summary>
        internal static string EstasAqui {
            get {
                return ResourceManager.GetString("EstasAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al crear el hilo.
        /// </summary>
        internal static string FalloCrearHilo {
            get {
                return ResourceManager.GetString("FalloCrearHilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fecha de creación.
        /// </summary>
        internal static string fechacreacion {
            get {
                return ResourceManager.GetString("fechacreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de ingreso.
        /// </summary>
        internal static string FechaIngreso {
            get {
                return ResourceManager.GetString("FechaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fecha de última respuesta.
        /// </summary>
        internal static string fecharespuesta {
            get {
                return ResourceManager.GetString("fecharespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firma.
        /// </summary>
        internal static string Firma {
            get {
                return ResourceManager.GetString("Firma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firmar.
        /// </summary>
        internal static string Firmar {
            get {
                return ResourceManager.GetString("Firmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firmas.
        /// </summary>
        internal static string Firmas {
            get {
                return ResourceManager.GetString("Firmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a firmas.
        /// </summary>
        internal static string FirmasMin {
            get {
                return ResourceManager.GetString("FirmasMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foro.
        /// </summary>
        internal static string Foro {
            get {
                return ResourceManager.GetString("Foro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Galería de fotos.
        /// </summary>
        internal static string GaleriaFotos {
            get {
                return ResourceManager.GetString("GaleriaFotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Galeria de usuario.
        /// </summary>
        internal static string GaleriaUsuario {
            get {
                return ResourceManager.GetString("GaleriaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        internal static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo creado correctamente.
        /// </summary>
        internal static string GrupoCreado {
            get {
                return ResourceManager.GetString("GrupoCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos.
        /// </summary>
        internal static string Grupos {
            get {
                return ResourceManager.GetString("Grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos del usuario.
        /// </summary>
        internal static string GruposUsuario {
            get {
                return ResourceManager.GetString("GruposUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        internal static string GuardarCambios {
            get {
                return ResourceManager.GetString("GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hilo.
        /// </summary>
        internal static string Hilo {
            get {
                return ResourceManager.GetString("Hilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hilo creado correctamente.
        /// </summary>
        internal static string HiloCreadoCorrectamente {
            get {
                return ResourceManager.GetString("HiloCreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hilos.
        /// </summary>
        internal static string Hilos {
            get {
                return ResourceManager.GetString("Hilos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identifícate para añadir una respuesta.
        /// </summary>
        internal static string IdentificateAnadirRespuesta {
            get {
                return ResourceManager.GetString("IdentificateAnadirRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorias a las que estas suscrito.
        /// </summary>
        internal static string InfoCategorias {
            get {
                return ResourceManager.GetString("InfoCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En tu página sólo se mostrará la encuesta activa más reciente.
        /// </summary>
        internal static string InfoEncuestas {
            get {
                return ResourceManager.GetString("InfoEncuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información adicional.
        /// </summary>
        internal static string InformacionAdicional {
            get {
                return ResourceManager.GetString("InformacionAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha inscrito correctamente al grupo.
        /// </summary>
        internal static string InscribirGrupo {
            get {
                return ResourceManager.GetString("InscribirGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insuscribirse.
        /// </summary>
        internal static string Insuscribirse {
            get {
                return ResourceManager.GetString("Insuscribirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insuscribirse de la categoría actual.
        /// </summary>
        internal static string InsuscribirseCategoriaActual {
            get {
                return ResourceManager.GetString("InsuscribirseCategoriaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leido.
        /// </summary>
        internal static string Leido {
            get {
                return ResourceManager.GetString("Leido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leído.
        /// </summary>
        internal static string Leído {
            get {
                return ResourceManager.GetString("Leído", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string Limpiar {
            get {
                return ResourceManager.GetString("Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes hacer login para votar.
        /// </summary>
        internal static string LoginParaVotar {
            get {
                return ResourceManager.GetString("LoginParaVotar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material.
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Materiales.
        /// </summary>
        internal static string Materiales {
            get {
                return ResourceManager.GetString("Materiales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        internal static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado el mensaje correctamente al grupo.
        /// </summary>
        internal static string MensajeEnviadoGrupo {
            get {
                return ResourceManager.GetString("MensajeEnviadoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado el mensaje correctamente al usuario.
        /// </summary>
        internal static string MensajeEnviadoUsuario {
            get {
                return ResourceManager.GetString("MensajeEnviadoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe haber iniciado sesion para mandar un mensaje.
        /// </summary>
        internal static string MensajeErrorLogeado {
            get {
                return ResourceManager.GetString("MensajeErrorLogeado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede mandarse un mensaje a si mismo.
        /// </summary>
        internal static string MensajeErrorMismoUsuario {
            get {
                return ResourceManager.GetString("MensajeErrorMismoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje privado.
        /// </summary>
        internal static string MensajePrivado {
            get {
                return ResourceManager.GetString("MensajePrivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mensajes.
        /// </summary>
        internal static string MensajesMin {
            get {
                return ResourceManager.GetString("MensajesMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensajes privados.
        /// </summary>
        internal static string MensajesPrivados {
            get {
                return ResourceManager.GetString("MensajesPrivados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a miembros.
        /// </summary>
        internal static string miembros {
            get {
                return ResourceManager.GetString("miembros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miembros.
        /// </summary>
        internal static string MiembrosMayus {
            get {
                return ResourceManager.GetString("MiembrosMayus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Votos.
        /// </summary>
        internal static string MVotos {
            get {
                return ResourceManager.GetString("MVotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nadie.
        /// </summary>
        internal static string nadie {
            get {
                return ResourceManager.GetString("nadie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay encuestas activas.
        /// </summary>
        internal static string NoEncuestasActivas {
            get {
                return ResourceManager.GetString("NoEncuestasActivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está apuntado a ningún grupo.
        /// </summary>
        internal static string NoEstaApuntadoNingunGrupo {
            get {
                return ResourceManager.GetString("NoEstaApuntadoNingunGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este usuario no tiene firmas.
        /// </summary>
        internal static string NoFirmas {
            get {
                return ResourceManager.GetString("NoFirmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay subcategorías en esta categoría.
        /// </summary>
        internal static string NoHayCategorias {
            get {
                return ResourceManager.GetString("NoHayCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        internal static string NombreCompleto {
            get {
                return ResourceManager.GetString("NombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tengo mensajes privados.
        /// </summary>
        internal static string NoMensajes {
            get {
                return ResourceManager.GetString("NoMensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de respuestas.
        /// </summary>
        internal static string NRespuestas {
            get {
                return ResourceManager.GetString("NRespuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        internal static string NuevaContraseña {
            get {
                return ResourceManager.GetString("NuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva encuesta.
        /// </summary>
        internal static string NuevaEncuesta {
            get {
                return ResourceManager.GetString("NuevaEncuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva opción.
        /// </summary>
        internal static string NuevaOpcion {
            get {
                return ResourceManager.GetString("NuevaOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo material.
        /// </summary>
        internal static string NuevoMaterial {
            get {
                return ResourceManager.GetString("NuevoMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imágenes.
        /// </summary>
        internal static string NumeroImagenes {
            get {
                return ResourceManager.GetString("NumeroImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de respuestas.
        /// </summary>
        internal static string NumeroRespuestas {
            get {
                return ResourceManager.GetString("NumeroRespuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Usuarios.
        /// </summary>
        internal static string NUsuarios {
            get {
                return ResourceManager.GetString("NUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opcion.
        /// </summary>
        internal static string Opcion {
            get {
                return ResourceManager.GetString("Opcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar por.
        /// </summary>
        internal static string OrdenarPor {
            get {
                return ResourceManager.GetString("OrdenarPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de inicio.
        /// </summary>
        internal static string PaginaInicio {
            get {
                return ResourceManager.GetString("PaginaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para.
        /// </summary>
        internal static string Para {
            get {
                return ResourceManager.GetString("Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a por.
        /// </summary>
        internal static string por {
            get {
                return ResourceManager.GetString("por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta.
        /// </summary>
        internal static string Pregunta {
            get {
                return ResourceManager.GetString("Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pulse aquí para volver.
        /// </summary>
        internal static string PulsarVolver {
            get {
                return ResourceManager.GetString("PulsarVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuación.
        /// </summary>
        internal static string Puntuacion {
            get {
                return ResourceManager.GetString("Puntuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        internal static string Quitar {
            get {
                return ResourceManager.GetString("Quitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia.
        /// </summary>
        internal static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta.
        /// </summary>
        internal static string Respuesta {
            get {
                return ResourceManager.GetString("Respuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuestas.
        /// </summary>
        internal static string Respuestas {
            get {
                return ResourceManager.GetString("Respuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a número de respuestas.
        /// </summary>
        internal static string respuestasminusculas {
            get {
                return ResourceManager.GetString("respuestasminusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados.
        /// </summary>
        internal static string Resultados {
            get {
                return ResourceManager.GetString("Resultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una categoría para crear un hilo.
        /// </summary>
        internal static string SeleccionaCategoriaCrearHilo {
            get {
                return ResourceManager.GetString("SeleccionaCategoriaCrearHilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suscribirse a la categoría actual.
        /// </summary>
        internal static string SuscribirseCategoriaActual {
            get {
                return ResourceManager.GetString("SuscribirseCategoriaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        internal static string Tamaño {
            get {
                return ResourceManager.GetString("Tamaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        internal static string Texto {
            get {
                return ResourceManager.GetString("Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a la edición web de CacatUA.
        /// </summary>
        internal static string TextoInicial {
            get {
                return ResourceManager.GetString("TextoInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a título.
        /// </summary>
        internal static string titulominusculas {
            get {
                return ResourceManager.GetString("titulominusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total votos.
        /// </summary>
        internal static string TotalVotos {
            get {
                return ResourceManager.GetString("TotalVotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última respuesta.
        /// </summary>
        internal static string UltimaRespuesta {
            get {
                return ResourceManager.GetString("UltimaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Últimos hilos.
        /// </summary>
        internal static string UltimosHilos {
            get {
                return ResourceManager.GetString("UltimosHilos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Últimos materiales.
        /// </summary>
        internal static string UltimosMateriales {
            get {
                return ResourceManager.GetString("UltimosMateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Últimos usuarios registrados.
        /// </summary>
        internal static string UltimosUsuarios {
            get {
                return ResourceManager.GetString("UltimosUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario registrado correctamente.
        /// </summary>
        internal static string UsuarioRegistrado {
            get {
                return ResourceManager.GetString("UsuarioRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuarios.
        /// </summary>
        internal static string UsuariosMin {
            get {
                return ResourceManager.GetString("UsuariosMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver el hilo.
        /// </summary>
        internal static string VerHilo {
            get {
                return ResourceManager.GetString("VerHilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viendo.
        /// </summary>
        internal static string Viendo {
            get {
                return ResourceManager.GetString("Viendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visitas.
        /// </summary>
        internal static string Visitas {
            get {
                return ResourceManager.GetString("Visitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a número de visitas.
        /// </summary>
        internal static string visitasminusculas {
            get {
                return ResourceManager.GetString("visitasminusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a encuestas.
        /// </summary>
        internal static string VolverEncuestas {
            get {
                return ResourceManager.GetString("VolverEncuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al foro.
        /// </summary>
        internal static string VolverForo {
            get {
                return ResourceManager.GetString("VolverForo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Votar.
        /// </summary>
        internal static string Votar {
            get {
                return ResourceManager.GetString("Votar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a votos.
        /// </summary>
        internal static string Votos {
            get {
                return ResourceManager.GetString("Votos", resourceCulture);
            }
        }
    }
}
