//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.I18N", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir respuesta.
        /// </summary>
        internal static string AnadirRespuesta {
            get {
                return ResourceManager.GetString("AnadirRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir una respuesta.
        /// </summary>
        internal static string AnadirUnaRespuesta {
            get {
                return ResourceManager.GetString("AnadirUnaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        internal static string Anterior {
            get {
                return ResourceManager.GetString("Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apuntarse.
        /// </summary>
        internal static string Apuntarse {
            get {
                return ResourceManager.GetString("Apuntarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ascendente.
        /// </summary>
        internal static string ascendente {
            get {
                return ResourceManager.GetString("ascendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        internal static string autormensaje {
            get {
                return ResourceManager.GetString("autormensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string CabeceraEdicionEncuestasFecha {
            get {
                return ResourceManager.GetString("CabeceraEdicionEncuestasFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta.
        /// </summary>
        internal static string CabeceraEdicionEncuestasPregunta {
            get {
                return ResourceManager.GetString("CabeceraEdicionEncuestasPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad por página.
        /// </summary>
        internal static string CantidadPorPagina {
            get {
                return ResourceManager.GetString("CantidadPorPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        internal static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías.
        /// </summary>
        internal static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creado por.
        /// </summary>
        internal static string creadoPor {
            get {
                return ResourceManager.GetString("creadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nuevo hilo.
        /// </summary>
        internal static string CrearNuevoHilo {
            get {
                return ResourceManager.GetString("CrearNuevoHilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes identificarte.
        /// </summary>
        internal static string DebesIdentificarte {
            get {
                return ResourceManager.GetString("DebesIdentificarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desapuntarse.
        /// </summary>
        internal static string Desapuntarse {
            get {
                return ResourceManager.GetString("Desapuntarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        internal static string Descargar {
            get {
                return ResourceManager.GetString("Descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargas.
        /// </summary>
        internal static string Descargas {
            get {
                return ResourceManager.GetString("Descargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descendente.
        /// </summary>
        internal static string descendente {
            get {
                return ResourceManager.GetString("descendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la categoría actual.
        /// </summary>
        internal static string EnCategoriaActual {
            get {
                return ResourceManager.GetString("EnCategoriaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En todas las categorías.
        /// </summary>
        internal static string EnTodasCategorias {
            get {
                return ResourceManager.GetString("EnTodasCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Mensaje.
        /// </summary>
        internal static string Enviarmensaje {
            get {
                return ResourceManager.GetString("Enviarmensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar respuesta.
        /// </summary>
        internal static string EnviarRespuesta {
            get {
                return ResourceManager.GetString("EnviarRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estás aquí.
        /// </summary>
        internal static string EstasAqui {
            get {
                return ResourceManager.GetString("EstasAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fecha de creación.
        /// </summary>
        internal static string fechacreacion {
            get {
                return ResourceManager.GetString("fechacreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de ingreso.
        /// </summary>
        internal static string FechaIngreso {
            get {
                return ResourceManager.GetString("FechaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fecha de última respuesta.
        /// </summary>
        internal static string fecharespuesta {
            get {
                return ResourceManager.GetString("fecharespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foro.
        /// </summary>
        internal static string Foro {
            get {
                return ResourceManager.GetString("Foro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        internal static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos.
        /// </summary>
        internal static string Grupos {
            get {
                return ResourceManager.GetString("Grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilo.
        /// </summary>
        internal static string Hilo {
            get {
                return ResourceManager.GetString("Hilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilos.
        /// </summary>
        internal static string Hilos {
            get {
                return ResourceManager.GetString("Hilos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        internal static string Limpiar {
            get {
                return ResourceManager.GetString("Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiales.
        /// </summary>
        internal static string Materiales {
            get {
                return ResourceManager.GetString("Materiales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        internal static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nadie.
        /// </summary>
        internal static string nadie {
            get {
                return ResourceManager.GetString("nadie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay subcategorías en esta categoría.
        /// </summary>
        internal static string NoHayCategorias {
            get {
                return ResourceManager.GetString("NoHayCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de respuestas.
        /// </summary>
        internal static string NRespuestas {
            get {
                return ResourceManager.GetString("NRespuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de respuestas.
        /// </summary>
        internal static string NumeroRespuestas {
            get {
                return ResourceManager.GetString("NumeroRespuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar por.
        /// </summary>
        internal static string OrdenarPor {
            get {
                return ResourceManager.GetString("OrdenarPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página de inicio.
        /// </summary>
        internal static string PaginaInicio {
            get {
                return ResourceManager.GetString("PaginaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to por.
        /// </summary>
        internal static string por {
            get {
                return ResourceManager.GetString("por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntuación.
        /// </summary>
        internal static string Puntuacion {
            get {
                return ResourceManager.GetString("Puntuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta.
        /// </summary>
        internal static string Respuesta {
            get {
                return ResourceManager.GetString("Respuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuestas.
        /// </summary>
        internal static string Respuestas {
            get {
                return ResourceManager.GetString("Respuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to número de respuestas.
        /// </summary>
        internal static string respuestasminusculas {
            get {
                return ResourceManager.GetString("respuestasminusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        internal static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño.
        /// </summary>
        internal static string Tamaño {
            get {
                return ResourceManager.GetString("Tamaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        internal static string Texto {
            get {
                return ResourceManager.GetString("Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a la edición web de CacatUA.
        /// </summary>
        internal static string TextoInicial {
            get {
                return ResourceManager.GetString("TextoInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to título.
        /// </summary>
        internal static string titulominusculas {
            get {
                return ResourceManager.GetString("titulominusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última respuesta.
        /// </summary>
        internal static string UltimaRespuesta {
            get {
                return ResourceManager.GetString("UltimaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitas.
        /// </summary>
        internal static string Visitas {
            get {
                return ResourceManager.GetString("Visitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to número de visitas.
        /// </summary>
        internal static string visitasminusculas {
            get {
                return ResourceManager.GetString("visitasminusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to votes.
        /// </summary>
        internal static string Votos {
            get {
                return ResourceManager.GetString("Votos", resourceCulture);
            }
        }
    }
}
